SHEETS_TO_PROCESS: list[str] = ["P&B"]

# ignore columns with this regular expression
COLUMNS_TO_DROP_RE_EXPRESSION: list[str] = [r"(?i)FY\d{2}"]


# Mapping between metric descriptions and PI tags.
TAG_MAPPING = {
    "Alumina Produced, T": "HIL_ALU_RKT_REF_UTILT_MNL_ALU_PROD",
    "Alumina Calcined, T": "HIL_ALU_RKT_REF_UTILT_MNL_ALU_CALCN",
    "Vanadium Sludge, T": "HIL_ALU_RKT_REF_UTILT_MNL_VAND_SLDG",
    "Recovery Factor": "HIL_ALU_RKT_REF_UTILT_MNL_RECVRY_FACTR",
    "Month days ": "HIL_ALU_RKT_REF_UTILT_MNL_MNTH_DAYS",
    "Flowcuts/Process Upsets": "HIL_ALU_RKT_REF_UTILT_MNL_FLCUTS_OR_PROCESS_UPSETS",
    "Short Shutdowns": "HIL_ALU_RKT_REF_UTILT_MNL_SHORT_SHUTDOWNS",
    "Annual Shut down": "HIL_ALU_RKT_REF_UTILT_MNL_ANNUAL_SHUT_DOWN",
    "No. of operation days ": "HIL_ALU_RKT_REF_UTILT_MNL_NUM_OF_OP_DAYS",
    "Plant Availability factor%": "HIL_ALU_RKT_REF_UTILT_MNL_PLNT_AVAIL_FACTR",
    "Steam – T/T": "HIL_ALU_RKT_REF_UTILT_MNL_STM",
    "Power  - KWH/T": "HIL_ALU_RKT_REF_UTILT_MNL_PWR",
    "Fuel Oil – Kg/T": "HIL_ALU_RKT_REF_UTILT_MNL_FUEL_OIL",
    "Bauxite (As is)  - T/T (theoretical)": "HIL_ALU_RKT_REF_UTILT_MNL_BAUX_AS_IS_THEOR",
    "Bauxite (As is)  - T/T": "HIL_ALU_RKT_REF_UTILT_MNL_BAUX_AS_IS",
    "Caustic Soda  – T/T": "HIL_ALU_RKT_REF_UTILT_MNL_CAUS_SODA",
    "Lime  - T/T": "HIL_ALU_RKT_REF_UTILT_MNL_LIME",
    "C.G.M.  - g/T ": "HIL_ALU_RKT_REF_UTILT_MNL_CGM",
    "Scale guard -gm/T": "HIL_ALU_RKT_REF_UTILT_MNL_SCALE_GUARD",
    "Antifoam-g/T": "HIL_ALU_RKT_REF_UTILT_MNL_ANTIFOAM",
    "Nalco-85700 ,Hydrate floc-gm/T": "HIL_ALU_RKT_REF_UTILT_MNL_NALCO_85700_AND_HYD_FLOC",
    "HRD Flocculant – g/T": "HIL_ALU_RKT_REF_UTILT_MNL_HRD_FLOC",
    "PD Floc-g/T": "HIL_ALU_RKT_REF_UTILT_MNL_PD_FLOC",
    "DCW -g/T": "HIL_ALU_RKT_REF_UTILT_MNL_DCW",
    "Washer Flocculant – g/T": "HIL_ALU_RKT_REF_UTILT_MNL_WSH_FLOC",
    "Defoamer – g/T": "HIL_ALU_RKT_REF_UTILT_MNL_DEFOAMER",
    "Max HT-g/T": "HIL_ALU_RKT_REF_UTILT_MNL_MAX_HTR",
    "Filter Cloth (Kelly) - Mt./T": "HIL_ALU_RKT_REF_UTILT_MNL_FLTR_CLTH_KELLY",
    "Filter Cloth (Diastar) - Mt./T": "HIL_ALU_RKT_REF_UTILT_MNL_FLTR_CLTH_DIASTR",
    "Water (T/T)": "HIL_ALU_RKT_REF_UTILT_MNL_WTR",
    "O'All TAA %": "HIL_ALU_RKT_REF_UTILT_MNL_O_ALL_TAA_PERCENT",
    "O'All SiO2  %": "HIL_ALU_RKT_REF_UTILT_MNL_O_ALL_SIO2_PERCENT",
    "O'All Moist. %": "HIL_ALU_RKT_REF_UTILT_MNL_O_ALL_MOIST_PERCENT",
    "Ex. Eff": "HIL_ALU_RKT_REF_UTILT_MNL_EXT_EFFICENCY",
    "Yeild": "HIL_ALU_RKT_REF_UTILT_MNL_YEILD",
    "Red Mud Generation": "HIL_ALU_RKT_REF_UTILT_MNL_RED_MUD_GEN",
    "Red Mud Utilization": "HIL_ALU_RKT_REF_UTILT_MNL_RED_MUD_UTILZ",
    "Overall Recovery": "HIL_ALU_RKT_REF_UTILT_MNL_OVER_RECVRY",
    "THA": "HIL_ALU_RKT_REF_UTILT_MNL_THA",
    "MHA": "HIL_ALU_RKT_REF_UTILT_MNL_MHA",
    "Chemical Extraction": "HIL_ALU_RKT_REF_UTILT_MNL_CHEM_EXTRCT",
    "Operating Efficiency (Production Basis) - (Production/Design)": "HIL_ALU_RKT_REF_UTILT_MNL_OP_EFFICENCY_PROD_BASIS_MINUS_PROD_UPON_DESIGN",
    "Bauxite Factor without handling loss": "HIL_ALU_RKT_REF_UTILT_MNL_BAUX_FACTOR_WITHOUT_HANDLE_LOSS",
    "Bauxite Handling Loss": "HIL_ALU_RKT_REF_UTILT_MNL_BAUX_HANDLE_LOSS",
    "Soda in Liquor to RDA": "HIL_ALU_RKT_REF_UTILT_MNL_SODA_IN_LIQ_TO_RDA",
    "Caustic Soda Loss in Liquor with Residue": "HIL_ALU_RKT_REF_UTILT_MNL_CAUS_SODA_LOSS_IN_LIQ_WITH_RESIDUE",
    "Caustic Soda Loss with Alumina": "HIL_ALU_RKT_REF_UTILT_MNL_CAUS_SODA_LOSS_WITH_ALU",
    "Caustic Soda Loss with Vanadium": "HIL_ALU_RKT_REF_UTILT_MNL_CAUS_SODA_LOSS_WITH_VAND",
    "Caustic Soda Loss (Others)": "HIL_ALU_RKT_REF_UTILT_MNL_CAUS_SODA_LOSS_OTHER",
    "Power Consumption - Hydrate": "HIL_ALU_RKT_REF_UTILT_MNL_PWR_CONS_HYD",
    "Power Consumption - Calcination": "HIL_ALU_RKT_REF_UTILT_MNL_PWR_CONS_CALCN",
    "Energy Consumption - Hydrate": "HIL_ALU_RKT_REF_UTILT_MNL_ENRGY_CONS_HYD",
    "Energy Consumption - Calcination": "HIL_ALU_RKT_REF_UTILT_MNL_ENRGY_CONS_CALCN",
    "Total Energy Consumption": "HIL_ALU_RKT_REF_UTILT_MNL_TOT_ENRGY_CONS",
    "Digestion Feed (Caustic) Flow": "HIL_ALU_RKT_REF_UTILT_MNL_DIG_FD_CAUS_FL",
    "Digestion Feed Caustic Concentration": "HIL_ALU_RKT_REF_UTILT_MNL_DIG_FD_CAUS_CONC",
    "Digestion Feed A/C": "HIL_ALU_RKT_REF_UTILT_MNL_DIG_FD_ACC",
    "Blow Off A/C": "HIL_ALU_RKT_REF_UTILT_MNL_BL_OFF_ACC",
    "PGL Flow": "HIL_ALU_RKT_REF_UTILT_MNL_PGL_FL",
    "PGL Caustic Concentration": "HIL_ALU_RKT_REF_UTILT_MNL_PGL_CAUS_CONC",
    "PGL A/C": "HIL_ALU_RKT_REF_UTILT_MNL_PGL_ACC",
    "Spent Liquor A/C": "HIL_ALU_RKT_REF_UTILT_MNL_SPT_LIQ_ACC",
    "Vanadium Purity Target": "HIL_ALU_RKT_REF_WA_MNL_VAN_PURITY_TARGET",
    "Digestor Productivity Target": "HIL_ALU_RKT_REF_UTILT_MNL_DIG_PROD_TRGT",
    "Dry Bauxite feed target": "HIL_ALU_RKT_REF_UTILT_MNL_DRY_BAUX_FD_TRGT",
    "P&B Meralgram Quantity": "HIL_ALU_RKT_REF_UTILT_MNL_MQX_QTY_TGT",
    "P&B Meralgram Sio2": "HIL_ALU_RKT_REF_UTILT_MNL_MQX_SIO2_TGT",
    "P&B Meralgram TAA": "HIL_ALU_RKT_REF_UTILT_MNL_MQX_TAA_TGT",
    "P&B Richuguta Quantity": "HIL_ALU_RKT_REF_UTILT_MNL_RCGT_QTY_TGT",
    "P&B Richuguta Sio2": "HIL_ALU_RKT_REF_UTILT_MNL_RCGT_SIO2_TGT",
    "P&B Richuguta TAA": "HIL_ALU_RKT_REF_UTILT_MNL_RCGT_TAA_TGT",
    "P&B Samari Quantity": "HIL_ALU_RKT_REF_UTILT_MNL_SAMARI_QTY_TGT",
    "P&B Samari Sio2": "HIL_ALU_RKT_REF_UTILT_MNL_SAMARI_SIO2_TGT",
    "P&B Samari TAA": "HIL_ALU_RKT_REF_UTILT_MNL_SAMARI_TAA_TGT",
    "P&B Tori Quantity": "HIL_ALU_RKT_REF_UTILT_MNL_TORI_QTY_TGT",
    "P&B Tori Sio2": "HIL_ALU_RKT_REF_UTILT_MNL_TORI_SIO2_TGT",
    "P&B Tori TAA": "HIL_ALU_RKT_REF_UTILT_MNL_TORI_TAA_TGT",
}
