name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python

  build-and-attach:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run:  uv sync --all-extras --all-groups

      - name: Build exe
        run: uv run pyinstaller autoUFL.spec --clean

      - name: Upload exe to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/AutoUFL.exe
          tag_name: ${{ needs.release.outputs.tag_name }}